[aws]
s3_bucket_input_and_script=''
s3_bucket_output=''
region='{Same as your EC2 Instance Region}'
lambda_function_name=''
lambda_role_name=''
lambda_layer_name=''
lambda_schedule_rule_name=''
lambda_layer_version=''
glue_role_name=''
glue_crawler_name=''
ec2_ip_address='{Public IPv4 address}'
account_id='{12 digit account id}'
athena_db=''

[email]
sender=''
recipient='{For this project, please make sure it is the same as the sender email}'

[airflow]
dag_name=''

[superset]
container_name=''